version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    volumes:
     - .:/code
     - /code/node_modules
    environment:
      - REDISCLOUD_URL=http://redis:6379
    depends_on:
     - redis
  redis:
    image: redis:alpine